"""add driver_vibe and matatu_nickname to matatu_rides

Revision ID: d7a1ffd59786
Revises: 411dcafe5e82
Create Date: 2025-05-29 11:59:14.332513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a1ffd59786'
down_revision: Union[str, None] = '411dcafe5e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matatu_rides', sa.Column('driver_vibe', sa.String(), nullable=True))
    op.add_column('matatu_rides', sa.Column('matatu_nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matatu_rides', 'matatu_nickname')
    op.drop_column('matatu_rides', 'driver_vibe')
    # ### end Alembic commands ###
